name: Linting
on: push
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: npm ci
      - name: Lint
        uses: npm run lint
